"""Bake and extract animation curves for anim.

Requieres:
- CollectRigsControlInterface

"""
# Import future modules
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

# Import third-party modules
from future import standard_library

standard_library.install_aliases()
# Import built-in modules
from builtins import str

# Import third-party modules
from maya import cmds
from maya_pyblish_plugins import maya_ui
from maya_pyblish_plugins.tracking import (
    anim_version_stream_fields_overrides,
)
from maya_scene_io import get_temp_path
from pixo_pyblish import plugin_instances
from pyblish import api
from pymel import core
from studiolibrarymaya import animitem

# Import local modules
from pxo_rigging_kit import core as kit_core


EXT = ".anim"
ANIM_INST_DEFAULT_NMSP = "anim"


def _bake_anim(nodes, start_frame, end_frame, sample_by=1.0):
    """Bake given nodes' animation and remove from anim layers

    Args:
        nodes (:obj:`list` of :obj:`pymel.core.PyNode`): Nodes to bake.
        start_frame (float): Frame to begin baking on.
        end_frame (float): Frame to end baking on.
        sample_by (float, optional): Sample rate for bake. Defaults to 1.0.

    """
    anim_layers = cmds.ls(type="animLayer")
    core.bakeResults(
        nodes,
        time=[start_frame, end_frame],
        sampleBy=sample_by,
        resolveWithoutLayer=anim_layers,
        removeBakedAttributeFromLayer=True,
        sm=True,
    )


def _refactor_namespace(assetNamespace, root_nd):
    """
    Will refactor the namespace if it generated from a proxyReferenceAsset node.

    Args:
        assetNamespace(str): Current instance asset namespace
        root_nd(pmc.PyNode): Current root node.

    Returns:
        String: Refactored namespace or original
    """
    # We check if the current asset namespace is a valid namespace.
    # We assume that if the namespace inherit the ANIM_INST_DEFAULT_NMSP it is invalid
    # and generated by a proxyReferenceAsset node.
    # The proxyReferenceAsset node has no namespace and the collectors upfront store
    # the ANIM_INST_DEFAULT_NMSP as default.
    current_nmsp = str(assetNamespace)
    if ANIM_INST_DEFAULT_NMSP in current_nmsp:
        # We assume to find the correct rig root node under the proxyReferenceAsset node.
        rig_root_nd = root_nd.getChildren()[0]
        namespace = rig_root_nd.parentNamespace()
        if not namespace:
            raise ValueError(f"Rig root node {rig_root_nd} has no namespace")
        current_nmsp = namespace.split(":")[0]
    return current_nmsp


class ExtractAnimCurvesBakedRigs(api.InstancePlugin):
    """Extract and bake animation curves"""

    order = api.ExtractorOrder
    families = ["anim"]
    hosts = ["maya"]
    label = "Extract animation curves for baked rigs ({0})".format(EXT)
    targets = ["local"]
    optional = True
    active = True

    def process(self, instance):
        """Bake animation to rigs, export, and restore scene.

        Args:
            instance (pyblish.api.Instance): Instance to extract from.

        """
        bake_sample_by = kit_core.get_config("anim_curves:bake_sample_by")
        frame_range = instance.data.get(
            "frameRange", instance.context.data["frameRange"]
        )
        asset_namespace = instance.data.get("assetNamespace")
        root = instance.data.get("root")
        if not all([root, asset_namespace]):
            self.log.info(
                f"No root or asset_namespace found in these instance {instance.name}. Will skip bake."
            )
            return True
        # The anim instance delivers a "ctrl" key with all rig ctrls
        # But it seems it just doing it for rigs with the pxoAsset as top node.
        # But some older shows are still running on the old workflow with the container as top node [BUG][SG-102650]
        # So if we can not find this key we fall back to an older collector which delivers the anim controls also.
        # Old or new approach. One of them should give us the anim controls.
        anim_ctrl = instance.data.get("ctrl", [])
        if anim_ctrl:
            anim_ctrl = [node.getTransform() for node in anim_ctrl]
        anim_controls = anim_ctrl or instance.data.get("anim_controls", [])
        if not anim_controls:
            self.log.info(
                "No anim controls found for {0}. Will skip bake.".format(
                    instance.name
                )
            )
            return True
        with maya_ui.refresh_suspended():
            with core.UndoChunk():
                # We have to bake before we can use the studio library export.
                # So we are sure we exported all needed curve data.
                _bake_anim(
                    anim_controls,
                    frame_range[0],
                    frame_range[1],
                    bake_sample_by,
                )
            # Export
            export_controls = [
                str(node.name(long=True)) for node in anim_controls
            ]
            path = str(get_temp_path(EXT))
            # The real export with the studio library package.
            # This package handles the anim curves I/O
            # because it is designed to do it.
            # Also the animators are used to these and we can use the standard
            # studio library Qt gui as fall back.
            # For the future and for maya-2022-py3 we have to exchange these
            # with something different or tweak the studio library
            # repo for python3.
            # Potential candidate could be
            # https://gitlab.pixomondo.com/pixomondo/external/kiko/-/tree/master
            selected = cmds.ls(selection=True)
            cmds.select(clear=True)
            animitem.save(
                path,
                objects=export_controls,
                frameRange=[frame_range[0], frame_range[1]],
                bakeConnected=True,
                sampleBy=bake_sample_by,
            )
            cmds.select(selected)
            core.undo()
        version_stream_fields = anim_version_stream_fields_overrides(instance)
        version_stream_fields["component"] = "anim-curves"
        plugin_instances.ensure_extraction_data(instance)
        instance.data["extractionData"].append(
            {
                "assetNamespace": _refactor_namespace(asset_namespace, root),
                "extractionPath": path,
                "ext": EXT,
                "plugin": self.__class__.__name__,
                "publishedFileType": 789,  # A folder containing a Studio Library loadable item for Maya (pose + animation-curves)
                "versionStreamFields": version_stream_fields,
            }
        )
        self.log.info(
            "Animation curves baked for {0} to: {1}".format(instance.name, path)
        )
